
from enum import Enum


class ErrorTypes(Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    EXTENSION_NOT_FOUND = "EXTENSION_NOT_FOUND"
    EXTENSION_RELOAD_ERROR = "EXTENSION_RELOAD_ERROR"
    EXTENSION_UNLOAD_ERROR = "EXTENSION_UNLOAD_ERROR"
    EXTENSION_LOAD_ERROR = "EXTENSION_LOAD_ERROR"
    UNKNOWN = "UNKNOWN"